### ISSUE TITLE
can't install istio in 9-vm-workloads

### ISSUE THREAD

**Issue by liyihuang** [tetratelabs/istio-training#3]
Hi,

I was not able to install the istio with the following provided in the training material.

➜  bin ./istioctl install --set values.pilot.env.PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION=true
This will install the Istio 1.9.5  profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istiod
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgateway
^C
➜  bin
➜  bin kubectl get pods -A
NAMESPACE      NAME                                                       READY   STATUS              RESTARTS   AGE
istio-system   istio-ingressgateway-85c449d886-5bcjl                      0/1     ContainerCreating   0          60s
istio-system   istiod-6fc675d854-z8pv2                                    0/1     Pending             0          6m2s
kube-system    event-exporter-gke-67986489c8-jtcd2                        2/2     Running             0          7m58s
kube-system    fluentbit-gke-fqfjs                                        2/2     Running             0          7m45s
kube-system    fluentbit-gke-gzjgj                                        2/2     Running             0          7m43s
kube-system    fluentbit-gke-tv6z9                                        2/2     Running             0          7m44s
kube-system    gke-metrics-agent-dkf9w                                    1/1     Running             0          7m44s
kube-system    gke-metrics-agent-jwmxq                                    1/1     Running             0          7m44s
kube-system    gke-metrics-agent-z755z                                    1/1     Running             0          7m43s
kube-system    kube-dns-6c7b8dc9f9-5dzz4                                  4/4     Running             0          7m53s
kube-system    kube-dns-6c7b8dc9f9-mmm57                                  4/4     Running             0          7m36s
kube-system    kube-dns-autoscaler-844c9d9448-d6bcq                       1/1     Running             0          7m53s
kube-system    kube-proxy-gke-liyihuang-default-pool-6470dcb4-1g5j        1/1     Running             0          7m40s
kube-system    kube-proxy-gke-liyihuang-default-pool-6470dcb4-6t25        1/1     Running             0          6m39s
kube-system    kube-proxy-gke-liyihuang-default-pool-6470dcb4-lxmm        1/1     Running             0          6m50s
kube-system    l7-default-backend-56cb9644f6-qn2gb                        1/1     Running             0          7m59s
kube-system    metrics-server-v0.3.6-9c5bbf784-q8hcg                      2/2     Running             0          7m1s
kube-system    pdcsi-node-2zsqj                                           2/2     Running             0          7m43s
kube-system    pdcsi-node-5g8xq                                           2/2     Running             0          7m45s
kube-system    pdcsi-node-8tpcq                                           2/2     Running             0          7m44s
kube-system    stackdriver-metadata-agent-cluster-level-cb4c6df9c-wwp7h   2/2     Running             0          7m3s
➜  bin kubectl get nodes
NAME                                       STATUS   ROLES    AGE     VERSION
gke-liyihuang-default-pool-6470dcb4-1g5j   Ready    <none>   9m10s   v1.20.8-gke.900
gke-liyihuang-default-pool-6470dcb4-6t25   Ready    <none>   9m11s   v1.20.8-gke.900
gke-liyihuang-default-pool-6470dcb4-lxmm   Ready    <none>   9m10s   v1.20.8-gke.900

btw, it's a brand new GKE cluster

**Comment by peterj** [comment]
I've updated the lab to use the latest Istio version, so this should be working now.
